export class LobbyPanelUI {
  constructor(onState,onColor=()=>{}){this.onState=onState;this.onColor=onColor;this.current=null;this.escape=event=>{if(event.key==='Escape'&&this.current){event.preventDefault();if(this.customizing)this.showLaptopHome();else this.hide()}};this.click=event=>{const color=event.target.closest('[data-character-color]');if(color){this.onColor(color.dataset.characterColor);this.selectColor(color.dataset.characterColor);return}if(event.target.closest('[data-customize-character]')){this.showCustomize();return}if(event.target.closest('[data-customize-back]')){this.showLaptopHome();return}if(event.target.closest('[data-lobby-close]'))this.hide()};addEventListener('keydown',this.escape);document.addEventListener('click',this.click)}
  show(id){const panel=document.querySelector(`[data-lobby-panel="${id}"]`);if(!panel)return;this.hide(false);this.current=panel;this.customizing=false;this.showLaptopHome();panel.classList.add('open');panel.setAttribute('aria-hidden','false');this.onState(true);requestAnimationFrame(()=>panel.querySelector('button:not([disabled])')?.focus())}
  showCustomize(){if(!this.current?.matches('[data-lobby-panel="laptop"]'))return;this.customizing=true;this.current.querySelector('[data-laptop-home]').hidden=true;this.current.querySelector('[data-character-customizer]').hidden=false;requestAnimationFrame(()=>this.current.querySelector('[data-character-color]')?.focus())}
  showLaptopHome(){if(!this.current?.matches('[data-lobby-panel="laptop"]'))return;this.customizing=false;this.current.querySelector('[data-laptop-home]').hidden=false;this.current.querySelector('[data-character-customizer]').hidden=true}
  selectColor(hex){this.current?.querySelectorAll('[data-character-color]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.characterColor.toLowerCase()===hex.toLowerCase())))}
  hide(notify=true){if(!this.current)return;this.current.classList.remove('open');this.current.setAttribute('aria-hidden','true');this.current=null;if(notify)this.onState(false)}
  toast(message){const toast=document.querySelector('#lobby-toast');toast.textContent=message;toast.classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>toast.classList.remove('visible'),2600)}
  dispose(){clearTimeout(this.toastTimer);this.hide();removeEventListener('keydown',this.escape);document.removeEventListener('click',this.click)}
}
