import {CharacterVisualController,CharacterVisualState} from './CharacterVisualController.js';

export {CharacterVisualState};
export const LOBBY_SPAWN=Object.freeze({position:Object.freeze({x:0,y:1.72,z:-4.5}),target:Object.freeze({x:0,y:1.55,z:1})});

export class PlayerController{
  constructor(scene,canvas,spawn=LOBBY_SPAWN){
    this.scene=scene;this.canvas=canvas;this.enabled=true;this.mobile=matchMedia('(pointer: coarse)').matches;this.move={x:0,y:0};this.keys=new Set();this.visualOverride=null;this.time=0;this.interactionAnimation=0;this.jumpImpulse=0;this.landReaction=0;this.grounded=true;this.wasGrounded=true;this.smoothedVelocity=new BABYLON.Vector2();
    const {position,target}=spawn;
    this.camera=new BABYLON.UniversalCamera('PlayerCamera',new BABYLON.Vector3(position.x,position.y,position.z),scene);this.camera.setTarget(new BABYLON.Vector3(target.x,target.y,target.z));this.camera.minZ=.045;this.camera.maxZ=90;this.camera.fov=BABYLON.Tools.ToRadians(70);this.camera.speed=.135;this.camera.inertia=.66;this.camera.angularSensibility=3000;this.camera.applyGravity=true;this.camera.checkCollisions=true;this.camera.ellipsoid.set(.42,.86,.42);this.camera.ellipsoidOffset.set(0,-.86,0);this.camera.keysUp=[87];this.camera.keysDown=[83];this.camera.keysLeft=[65];this.camera.keysRight=[68];this.camera.attachControl(canvas,true);this.camera.inputs.attached.mouse.buttons=[0];scene.activeCamera=this.camera;
    this.createBody();this.visuals=new CharacterVisualController(scene,this.camera,[this.torso,this.head,...this.bodyColorMeshes]);this.setupPointerLock();this.setupJump();this.setupTouch();
  }
  makeMaterial(name,hex){const m=new BABYLON.StandardMaterial(name,this.scene),c=BABYLON.Color3.FromHexString(hex);m.diffuseColor=c;m.ambientColor=c.scale(.42);m.emissiveColor=c.scale(.045);m.specularColor=new BABYLON.Color3(.035,.035,.035);return m}
  createBody(){
    this.playerRoot=new BABYLON.TransformNode('PlayerRoot',this.scene);this.body=new BABYLON.TransformNode('Body',this.scene);this.body.parent=this.playerRoot;
    this.skinMaterial=this.makeMaterial('configurable player color','#e7a26f');this.clothMaterial=this.makeMaterial('soft expedition suit','#587aa0');this.bootMaterial=this.makeMaterial('rubber boots','#34434c');
    const capsule=(name,parent,p,height,radius,material)=>{const m=BABYLON.MeshBuilder.CreateCapsule(name,{height,radius,tessellation:8},this.scene);m.parent=parent;m.position.set(...p);m.material=material;m.isPickable=false;m.checkCollisions=false;return m};
    this.torso=BABYLON.MeshBuilder.CreateSphere('Torso',{diameter:1,segments:8},this.scene);this.torso.parent=this.body;this.torso.position.y=-1.05;this.torso.scaling.set(.52,.68,.34);this.torso.material=this.clothMaterial;this.torso.isPickable=false;
    this.head=BABYLON.MeshBuilder.CreateSphere('Head',{diameter:.72,segments:8},this.scene);this.head.parent=this.body;this.head.position.y=-.28;this.head.material=this.skinMaterial;this.head.isVisible=false;
    this.leftArm=new BABYLON.TransformNode('LeftArm',this.scene);this.rightArm=new BABYLON.TransformNode('RightArm',this.scene);this.leftArm.parent=this.body;this.rightArm.parent=this.body;
    this.leftHand=new BABYLON.TransformNode('LeftHand',this.scene);this.rightHand=new BABYLON.TransformNode('RightHand',this.scene);this.leftHand.parent=this.leftArm;this.rightHand.parent=this.rightArm;
    this.leftLeg=new BABYLON.TransformNode('LeftLeg',this.scene);this.rightLeg=new BABYLON.TransformNode('RightLeg',this.scene);this.leftLeg.parent=this.body;this.rightLeg.parent=this.body;
    const leftLegVisual=capsule('left leg visual',this.leftLeg,[-.22,-1.4,0],.72,.16,this.clothMaterial),rightLegVisual=capsule('right leg visual',this.rightLeg,[.22,-1.4,0],.72,.16,this.clothMaterial);this.bodyColorMeshes=[leftLegVisual,rightLegVisual];capsule('left foot',this.leftLeg,[-.22,-1.69,.13],.4,.18,this.bootMaterial).rotation.x=Math.PI/2;capsule('right foot',this.rightLeg,[.22,-1.69,.13],.4,.18,this.bootMaterial).rotation.x=Math.PI/2;
  }
  setCharacterColor(hex){this.visuals.setColor(hex)}
  setVisualState(state){this.visualOverride=state;this.visuals.setState(state)}
  clearVisualState(){this.visualOverride=null}
  setupPointerLock(){this.click=()=>{if(this.enabled&&!this.mobile&&!document.pointerLockElement)this.canvas.requestPointerLock?.()};this.canvas.addEventListener('click',this.click)}
  setupJump(){this.jump=()=>{if(!this.enabled||!this.grounded)return;this.camera.cameraDirection.y=.16;this.grounded=false;this.jumpImpulse=1};this.keydown=e=>{this.keys.add(e.code);if(e.code==='Space'){e.preventDefault();this.jump()}};this.keyup=e=>this.keys.delete(e.code);addEventListener('keydown',this.keydown);addEventListener('keyup',this.keyup);this.jumpButton=document.querySelector('#mobile-jump');this.jumpButton?.addEventListener('pointerdown',this.jump)}
  setupTouch(){if(!this.mobile)return;const pad=document.querySelector('#move-pad'),knob=pad.querySelector('.move-knob'),look=document.querySelector('#look-pad');let moveId,lookId,lx=0,ly=0;this.touchEvents=new AbortController();const options={signal:this.touchEvents.signal};const reset=e=>{if(e.pointerId!==moveId)return;moveId=null;this.move={x:0,y:0};knob.style.transform=''};pad.addEventListener('pointerdown',e=>{moveId=e.pointerId;pad.setPointerCapture(moveId)},options);pad.addEventListener('pointermove',e=>{if(!this.enabled||e.pointerId!==moveId)return;const r=pad.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,d=Math.min(36,Math.hypot(x,y)),a=Math.atan2(y,x);this.move={x:Math.cos(a)*d/36,y:Math.sin(a)*d/36};knob.style.transform=`translate(${this.move.x*36}px,${this.move.y*36}px)`},options);pad.addEventListener('pointerup',reset,options);pad.addEventListener('pointercancel',reset,options);look.addEventListener('pointerdown',e=>{lookId=e.pointerId;lx=e.clientX;ly=e.clientY;look.setPointerCapture(lookId)},options);look.addEventListener('pointermove',e=>{if(!this.enabled||e.pointerId!==lookId)return;this.camera.rotation.y+=(e.clientX-lx)*.0036;this.camera.rotation.x=BABYLON.Scalar.Clamp(this.camera.rotation.x+(e.clientY-ly)*.0036,-1.35,1.35);lx=e.clientX;ly=e.clientY},options);const release=e=>{if(e.pointerId===lookId)lookId=null};look.addEventListener('pointerup',release,options);look.addEventListener('pointercancel',release,options)}
  playInteraction(){this.interactionAnimation=1}
  update(){
    const dt=Math.min(this.scene.getEngine().getDeltaTime()/1000,.04);this.time+=dt;this.camera.rotation.x=BABYLON.Scalar.Clamp(this.camera.rotation.x,-1.35,1.35);
    if(this.enabled&&this.mobile){const desired=new BABYLON.Vector2(this.move.x,-this.move.y);this.smoothedVelocity=BABYLON.Vector2.Lerp(this.smoothedVelocity,desired,1-Math.exp(-dt*11));const f=this.camera.getDirection(BABYLON.Axis.Z),r=this.camera.getDirection(BABYLON.Axis.X);f.y=0;r.y=0;this.camera.cameraDirection.addInPlace(f.scale(this.smoothedVelocity.y*.09)).addInPlace(r.scale(this.smoothedVelocity.x*.09))}
    const speed=this.mobile?Math.hypot(this.move.x,this.move.y):Math.hypot(this.camera.cameraDirection.x,this.camera.cameraDirection.z),moving=this.enabled&&speed>.012;this.grounded=this.camera.position.y<=1.74;if(this.grounded&&!this.wasGrounded)this.landReaction=1;this.wasGrounded=this.grounded;this.jumpImpulse=Math.max(0,this.jumpImpulse-dt*2.5);this.landReaction=Math.max(0,this.landReaction-dt*5);this.interactionAnimation=Math.max(0,this.interactionAnimation-dt*3.1);
    this.playerRoot.position.copyFrom(this.camera.position);this.playerRoot.rotation.y=this.camera.rotation.y;this.body.position.y=-.02+Math.sin(this.time*8)*.012*(moving?1:0);this.leftLeg.rotation.x=moving?Math.sin(this.time*8)*.18:0;this.rightLeg.rotation.x=-this.leftLeg.rotation.x;
    const running=moving&&(this.mobile?speed>.82:this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'));if(!this.visualOverride)this.visuals.setState(running?CharacterVisualState.RUNNING:moving?CharacterVisualState.WALKING:CharacterVisualState.IDLE);this.visuals.update(dt,this.time,this.interactionAnimation);
  }
  setEnabled(v){this.enabled=v;if(v)this.camera.attachControl(this.canvas,true);else{this.camera.detachControl();this.camera.cameraDirection.setAll(0)}if(!v&&document.pointerLockElement)document.exitPointerLock()}
  dispose(){this.canvas.removeEventListener('click',this.click);removeEventListener('keydown',this.keydown);removeEventListener('keyup',this.keyup);this.jumpButton?.removeEventListener('pointerdown',this.jump);this.touchEvents?.abort();this.visuals.dispose();this.camera.dispose();this.playerRoot.dispose()}
}
