export const LOBBY_SPAWN=Object.freeze({position:Object.freeze({x:0,y:1.72,z:-4.5}),target:Object.freeze({x:0,y:1.55,z:1})});

export class PlayerController{
  constructor(scene,canvas,spawn=LOBBY_SPAWN){
    this.scene=scene;this.canvas=canvas;this.enabled=true;this.mobile=matchMedia('(pointer: coarse)').matches;this.move={x:0,y:0};this.time=0;this.interactionAnimation=0;this.jumpImpulse=0;this.landReaction=0;this.grounded=true;this.wasGrounded=true;this.smoothedVelocity=new BABYLON.Vector2();
    const {position,target}=spawn;
    this.camera=new BABYLON.UniversalCamera('PlayerCamera',new BABYLON.Vector3(position.x,position.y,position.z),scene);this.camera.setTarget(new BABYLON.Vector3(target.x,target.y,target.z));this.camera.minZ=.045;this.camera.maxZ=90;this.camera.fov=BABYLON.Tools.ToRadians(70);this.camera.speed=.135;this.camera.inertia=.66;this.camera.angularSensibility=3000;this.camera.applyGravity=true;this.camera.checkCollisions=true;this.camera.ellipsoid.set(.42,.86,.42);this.camera.ellipsoidOffset.set(0,-.86,0);this.camera.keysUp=[87];this.camera.keysDown=[83];this.camera.keysLeft=[65];this.camera.keysRight=[68];this.camera.attachControl(canvas,true);this.camera.inputs.attached.mouse.buttons=[0];scene.activeCamera=this.camera;
    this.createBody();this.createViewArms();this.setupPointerLock();this.setupJump();this.setupTouch();
  }
  makeMaterial(name,hex){const m=new BABYLON.StandardMaterial(name,this.scene),c=BABYLON.Color3.FromHexString(hex);m.diffuseColor=c;m.ambientColor=c.scale(.42);m.emissiveColor=c.scale(.045);m.specularColor=new BABYLON.Color3(.035,.035,.035);return m}
  createBody(){
    this.playerRoot=new BABYLON.TransformNode('PlayerRoot',this.scene);this.body=new BABYLON.TransformNode('Body',this.scene);this.body.parent=this.playerRoot;
    this.skinMaterial=this.makeMaterial('configurable player color','#e7a26f');this.clothMaterial=this.makeMaterial('soft expedition suit','#587aa0');this.bootMaterial=this.makeMaterial('rubber boots','#34434c');
    const capsule=(name,parent,p,height,radius,material)=>{const m=BABYLON.MeshBuilder.CreateCapsule(name,{height,radius,tessellation:8},this.scene);m.parent=parent;m.position.set(...p);m.material=material;m.isPickable=false;m.checkCollisions=false;return m};
    this.torso=BABYLON.MeshBuilder.CreateSphere('Torso',{diameter:1,segments:8},this.scene);this.torso.parent=this.body;this.torso.position.y=-1.05;this.torso.scaling.set(.52,.68,.34);this.torso.material=this.clothMaterial;this.torso.isPickable=false;
    this.head=BABYLON.MeshBuilder.CreateSphere('Head',{diameter:.72,segments:8},this.scene);this.head.parent=this.body;this.head.position.y=-.28;this.head.material=this.skinMaterial;this.head.isVisible=false;
    this.leftArm=new BABYLON.TransformNode('LeftArm',this.scene);this.rightArm=new BABYLON.TransformNode('RightArm',this.scene);this.leftArm.parent=this.body;this.rightArm.parent=this.body;
    this.leftHand=new BABYLON.TransformNode('LeftHand',this.scene);this.rightHand=new BABYLON.TransformNode('RightHand',this.scene);this.leftHand.parent=this.leftArm;this.rightHand.parent=this.rightArm;
    this.leftLeg=new BABYLON.TransformNode('LeftLeg',this.scene);this.rightLeg=new BABYLON.TransformNode('RightLeg',this.scene);this.leftLeg.parent=this.body;this.rightLeg.parent=this.body;
    capsule('left leg visual',this.leftLeg,[-.22,-1.4,0],.72,.16,this.clothMaterial);capsule('right leg visual',this.rightLeg,[.22,-1.4,0],.72,.16,this.clothMaterial);capsule('left foot',this.leftLeg,[-.22,-1.69,.13],.4,.18,this.bootMaterial).rotation.x=Math.PI/2;capsule('right foot',this.rightLeg,[.22,-1.69,.13],.4,.18,this.bootMaterial).rotation.x=Math.PI/2;
  }
  createViewArms(){
    this.viewRoot=new BABYLON.TransformNode('FirstPersonArms',this.scene);this.viewRoot.parent=this.camera;
    const limb=(side)=>{const sign=side==='Left'?-1:1,root=new BABYLON.TransformNode(`View${side}Arm`,this.scene);root.parent=this.viewRoot;const arm=BABYLON.MeshBuilder.CreateCapsule(`${side} soft forearm`,{height:.58,radius:.105,tessellation:10},this.scene);arm.parent=root;arm.rotation.x=-.72;arm.rotation.z=-sign*.14;arm.material=this.clothMaterial;const handNode=new BABYLON.TransformNode(`View${side}Hand`,this.scene);handNode.parent=root;const palm=BABYLON.MeshBuilder.CreateSphere(`${side} rounded glove hand`,{diameter:.225,segments:10},this.scene);palm.parent=handNode;palm.scaling.set(1,.84,1.12);palm.material=this.skinMaterial;const thumb=BABYLON.MeshBuilder.CreateSphere(`${side} hand suggestion`,{diameter:.09,segments:7},this.scene);thumb.parent=handNode;thumb.position.set(-sign*.085,0,.025);thumb.scaling.y=.75;thumb.material=this.skinMaterial;[arm,palm,thumb].forEach(m=>{m.isPickable=false;m.checkCollisions=false;m.renderingGroupId=2;m.alwaysSelectAsActiveMesh=true});return {root,arm,handNode,palm,sign,baseX:0}};
    this.viewLeft=limb('Left');this.viewRight=limb('Right');this.viewRoot.position.z=.94;this.adaptViewArms();this.resize=()=>this.adaptViewArms();addEventListener('resize',this.resize);
  }
  adaptViewArms(){const engine=this.scene.getEngine(),aspect=engine.getRenderWidth()/Math.max(1,engine.getRenderHeight()),spread=BABYLON.Scalar.Clamp(.27+.12*(aspect-1),.25,.42);for(const limb of [this.viewLeft,this.viewRight]){limb.baseX=limb.sign*spread;limb.root.position.set(limb.baseX,-.42,.02);limb.handNode.position.set(0,.01,.3)}}
  setHandColor(hex){const c=BABYLON.Color3.FromHexString(hex);this.skinMaterial.diffuseColor=c;this.skinMaterial.ambientColor=c.scale(.42);this.skinMaterial.emissiveColor=c.scale(.045)}
  setupPointerLock(){this.click=()=>{if(this.enabled&&!this.mobile&&!document.pointerLockElement)this.canvas.requestPointerLock?.()};this.canvas.addEventListener('click',this.click)}
  setupJump(){this.jump=()=>{if(!this.enabled||!this.grounded)return;this.camera.cameraDirection.y=.16;this.grounded=false;this.jumpImpulse=1};this.keydown=e=>{if(e.code==='Space'){e.preventDefault();this.jump()}};addEventListener('keydown',this.keydown);this.jumpButton=document.querySelector('#mobile-jump');this.jumpButton?.addEventListener('pointerdown',this.jump)}
  setupTouch(){if(!this.mobile)return;const pad=document.querySelector('#move-pad'),knob=pad.querySelector('.move-knob'),look=document.querySelector('#look-pad');let moveId,lookId,lx=0,ly=0;this.touchEvents=new AbortController();const options={signal:this.touchEvents.signal};const reset=e=>{if(e.pointerId!==moveId)return;moveId=null;this.move={x:0,y:0};knob.style.transform=''};pad.addEventListener('pointerdown',e=>{moveId=e.pointerId;pad.setPointerCapture(moveId)},options);pad.addEventListener('pointermove',e=>{if(!this.enabled||e.pointerId!==moveId)return;const r=pad.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,d=Math.min(36,Math.hypot(x,y)),a=Math.atan2(y,x);this.move={x:Math.cos(a)*d/36,y:Math.sin(a)*d/36};knob.style.transform=`translate(${this.move.x*36}px,${this.move.y*36}px)`},options);pad.addEventListener('pointerup',reset,options);pad.addEventListener('pointercancel',reset,options);look.addEventListener('pointerdown',e=>{lookId=e.pointerId;lx=e.clientX;ly=e.clientY;look.setPointerCapture(lookId)},options);look.addEventListener('pointermove',e=>{if(!this.enabled||e.pointerId!==lookId)return;this.camera.rotation.y+=(e.clientX-lx)*.0036;this.camera.rotation.x=BABYLON.Scalar.Clamp(this.camera.rotation.x+(e.clientY-ly)*.0036,-1.35,1.35);lx=e.clientX;ly=e.clientY},options);const release=e=>{if(e.pointerId===lookId)lookId=null};look.addEventListener('pointerup',release,options);look.addEventListener('pointercancel',release,options)}
  playInteraction(){this.interactionAnimation=1}
  update(){
    const dt=Math.min(this.scene.getEngine().getDeltaTime()/1000,.04);this.time+=dt;this.camera.rotation.x=BABYLON.Scalar.Clamp(this.camera.rotation.x,-1.35,1.35);
    if(this.enabled&&this.mobile){const desired=new BABYLON.Vector2(this.move.x,-this.move.y);this.smoothedVelocity=BABYLON.Vector2.Lerp(this.smoothedVelocity,desired,1-Math.exp(-dt*11));const f=this.camera.getDirection(BABYLON.Axis.Z),r=this.camera.getDirection(BABYLON.Axis.X);f.y=0;r.y=0;this.camera.cameraDirection.addInPlace(f.scale(this.smoothedVelocity.y*.09)).addInPlace(r.scale(this.smoothedVelocity.x*.09))}
    const speed=this.mobile?Math.hypot(this.move.x,this.move.y):Math.hypot(this.camera.cameraDirection.x,this.camera.cameraDirection.z),moving=this.enabled&&speed>.012;this.grounded=this.camera.position.y<=1.74;if(this.grounded&&!this.wasGrounded)this.landReaction=1;this.wasGrounded=this.grounded;this.jumpImpulse=Math.max(0,this.jumpImpulse-dt*2.5);this.landReaction=Math.max(0,this.landReaction-dt*5);this.interactionAnimation=Math.max(0,this.interactionAnimation-dt*3.1);
    this.playerRoot.position.copyFrom(this.camera.position);this.playerRoot.rotation.y=this.camera.rotation.y;this.body.position.y=-.02+Math.sin(this.time*8)*.012*(moving?1:0);this.leftLeg.rotation.x=moving?Math.sin(this.time*8)*.18:0;this.rightLeg.rotation.x=-this.leftLeg.rotation.x;
    const walk=Math.sin(this.time*8)*(moving?.035:0),breathL=Math.sin(this.time*1.7)*.006,breathR=Math.sin(this.time*1.53+1.2)*.006,air=this.grounded?0:.035;for(const limb of [this.viewLeft,this.viewRight]){const opposite=walk*-limb.sign,targetX=limb.baseX+limb.sign*(air+this.jumpImpulse*.025);limb.root.position.x=BABYLON.Scalar.Lerp(limb.root.position.x,targetX,1-Math.exp(-dt*9));limb.root.position.y=-.42+(limb.sign<0?breathL:breathR)+opposite-this.jumpImpulse*.025+this.landReaction*.035;limb.root.rotation.x=BABYLON.Scalar.Lerp(limb.root.rotation.x,opposite*.8,1-Math.exp(-dt*8))}
    this.viewRight.handNode.position.z=.3+Math.sin(this.interactionAnimation*Math.PI)*.28;
  }
  setEnabled(v){this.enabled=v;if(v)this.camera.attachControl(this.canvas,true);else{this.camera.detachControl();this.camera.cameraDirection.setAll(0)}if(!v&&document.pointerLockElement)document.exitPointerLock()}
  dispose(){removeEventListener('resize',this.resize);this.canvas.removeEventListener('click',this.click);removeEventListener('keydown',this.keydown);this.jumpButton?.removeEventListener('pointerdown',this.jump);this.touchEvents?.abort();this.camera.dispose();this.playerRoot.dispose();this.viewRoot.dispose()}
}
